source 'https://cdn.cocoapods.org'
target 'Bisq Connect Debug' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'clientApp', :path => '../apps/clientApp'
end
target 'Bisq Connect' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'clientApp', :path => '../apps/clientApp'
end